export const GET_ELECTRONICS = "GET_ELECTRONICS"; 
export const GET_JEWELERY = "GET_JEWELERY"; 
export const GET_CLOTHING_M = "GET_CLOTHING_M"; 
export const GET_CLOTHING_F = "GET_CLOTHING_F"; 
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const CLEAN_SINGLE_PRODUCT = "CLEAN_SINGLE_PRODUCT";