export const GET_DATA = "GET_DATA";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const FILTER_BY_STOCK = "FILTER_BY_STOCK";
export const FILTER_BY_DELIVERY = "FILTER_BY_DELIVERY";
export const FILTER_BY_RATING = "FILTER_BY_RATING";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const CLEAR_FILTERS = "CLEAR_FILTERS"
